Added openfortivpn choices for my school's vpn

diff --git a/ArchLinux/Shell/.config/shell/script/vpn b/ArchLinux/Shell/.config/shell/script/vpn
--- a/ArchLinux/Shell/.config/shell/script/vpn
+++ b/ArchLinux/Shell/.config/shell/script/vpn
@@ -8,12 +8,18 @@ active_vpn=""
 printf "\033[1;36m%*s\033[0m\n" "$(tput cols)" "" | tr ' ' '='
 echo "WireGuard list:"
 nmcli -f NAME,TYPE,DEVICE conn show | awk '/wireguard/'
+echo "Unistra (OpenFortiVPN)"
 if nmcli -t -f NAME,TYPE connection show --active | grep -q ':wireguard$'; then
     active_vpn="$(nmcli -t -f NAME,TYPE connection show --active | awk -F: '$2=="wireguard"{print $1; exit}')"
     ifVpn=true
     printf "\033[38;2;255;165;0mThe following WireGuard is active: %s\033[0m\n" "$active_vpn"
 else
     printf "\033[38;2;255;165;0mNo active WireGuard connection.\033[0m\n"
+    if pgrep -x openfortivpn >/dev/null; then
+        active_vpn="Unistra"
+        ifVpn=true
+        printf "\033[38;2;255;165;0mThe following VPN connection is active: %s\033[0m\n" "$active_vpn"
+    fi
 fi
 printf "\033[1;36m%*s\033[0m\n" "$(tput cols)" "" | tr ' ' '='
 printf "\033[1;36m██╗   ██╗██████╗ ███╗   ██╗               󰍜 Main Menu:\033[0m\n"
@@ -39,20 +45,44 @@ case "${choice:-}" in
         vpn_conn_name="CH-Zurich"
     fi
 
-    # Check vpn profile's existence
+    # Check current VPN connection, if found any, disconnect
+    if [[ "$active_vpn" == "Unistra" ]]; then
+        sudo pkill -INT -x openfortivpn
+    elif [ -n "${active_vpn:-}" ]; then        
+        nmcli conn down "$active_vpn"
+    fi
+
+    # VPN connection
+    if [[ "$vpn_conn_name" == "Unistra" ]]; then
+        sudo openfortivpn -c "$HOME/.config/openfortivpn/config"
+        exit 0
+    fi
     if nmcli -g NAME,TYPE connection show | grep -Fxq "$vpn_conn_name:wireguard"; then 
-        if [ -n "${active_vpn:-}" ]; then
-            nmcli conn down "$active_vpn"
-        fi
         nmcli conn up "$vpn_conn_name"
         exit 0
     else
         printf "\033[1;31mVPN profile not found.\033[0m\n"
         exit 1
     fi
+
+    # Check wireguard vpn profile's existence
+    # if nmcli -g NAME,TYPE connection show | grep -Fxq "$vpn_conn_name:wireguard"; then 
+    #     if [ -n "${active_vpn:-}" ]; then        
+    #         nmcli conn down "$active_vpn"
+    #     fi
+    #     nmcli conn up "$vpn_conn_name"
+    #     exit 0 
+    # else
+    #     printf "\033[1;31mVPN profile not found.\033[0m\n"
+    #     exit 1
+    # fi
     ;;
   2)
     printf "\033[1;36m%*s\033[0m\n" "$(tput cols)" "" | tr ' ' '='
+    if [[ "$active_vpn" == "Unistra" ]]; then
+        sudo pkill -INT -x openfortivpn
+        exit 0
+    fi
     if [ -n "${active_vpn:-}" ]; then
         nmcli conn down "$active_vpn"
         exit 0
